[package]
name = "Rust-3D-Rendering"
version = "0.1.0"
authors = ["Karam Singh <karam.singh.vir@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.18"
